/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dictionary;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    
    public UserInterface() {
        initComponents();
        JOptionPane.showMessageDialog(rootPane, "This is a Storage Based small dictionary using JAVA SWING\n"
                + " for course assignment.\n"
                + "Here I have put only 60 words.\n"
                + "User can find Synonyms, Antonyms and Meaning  of these words only.\n"
                + "I have put the words in a word file so that user can use it easily.\n"
                + "Please check the Word file which is file kept in the main file.");
    }

    String arr[] = new String[500];
    String word, line, wlower;
    int meaning, synonym, antonym;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DictionaryLabel = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        MeaningRButton = new javax.swing.JRadioButton();
        SynonymRButton = new javax.swing.JRadioButton();
        AntonymRButton = new javax.swing.JRadioButton();
        ShowTextField = new javax.swing.JTextField();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DictionaryLabel.setBackground(new java.awt.Color(0, 153, 153));
        DictionaryLabel.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        DictionaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DictionaryLabel.setText("Dictionary");
        DictionaryLabel.setOpaque(true);
        jPanel1.add(DictionaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 30));

        SearchTextField.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        SearchTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 69, 0)));
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(SearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 350, 50));

        SearchButton.setBackground(new java.awt.Color(255, 255, 255));
        SearchButton.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 69, 0)));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 100, 50));

        buttonGroup.add(MeaningRButton);
        MeaningRButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        MeaningRButton.setText("Meaning");
        MeaningRButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 69, 0)));
        MeaningRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeaningRButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MeaningRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        buttonGroup.add(SynonymRButton);
        SynonymRButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        SynonymRButton.setText("Synonym");
        SynonymRButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 69, 0)));
        SynonymRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SynonymRButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SynonymRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        buttonGroup.add(AntonymRButton);
        AntonymRButton.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        AntonymRButton.setText("Antonym");
        AntonymRButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 69, 0)));
        AntonymRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntonymRButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AntonymRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        ShowTextField.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        ShowTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ShowTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ShowTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 490, 70));

        BackgroundLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 69, 0)));
        jPanel1.add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        word = SearchTextField.getText();
        wlower = word.toLowerCase();
        try {
            File file = new File("dictionary.txt");
            //file.createNewFile();
            BufferedReader br = new BufferedReader(new FileReader(file));

            while ((line = br.readLine()) != null) {
                arr = line.split("#");
                System.out.println(arr[0]);
                System.out.println(wlower);
                if ( meaning == 1 && arr[0].equals(wlower)) {
                    ShowTextField.setText(arr[1]);
                    break;
                } else if (synonym == 1 && arr[0].equals(wlower)) {
                    ShowTextField.setText(arr[2]);
                    break;
                } else if (antonym == 1 && arr[0].equals(wlower)) {
                    ShowTextField.setText(arr[3]);
                    break;
                }
                else {
                   ShowTextField.setText("The word is not in the Storage");
                 
                }
               
            }
        } catch (IOException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void MeaningRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeaningRButtonActionPerformed
        // TODO add your handling code here:
        meaning = 1;
        synonym = 0;
        antonym = 0;
        //ShowTextField.setText(word);
    }//GEN-LAST:event_MeaningRButtonActionPerformed

    private void SynonymRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SynonymRButtonActionPerformed
        // TODO add your handling code here:
        meaning = 0;
        synonym = 1;
        antonym = 0;
    }//GEN-LAST:event_SynonymRButtonActionPerformed

    private void AntonymRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntonymRButtonActionPerformed
        // TODO add your handling code here:
        meaning = 0;
        synonym = 0;
        antonym = 1;
    }//GEN-LAST:event_AntonymRButtonActionPerformed

    private void ShowTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowTextFieldActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AntonymRButton;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel DictionaryLabel;
    private javax.swing.JRadioButton MeaningRButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JTextField ShowTextField;
    private javax.swing.JRadioButton SynonymRButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void While(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
